### ISSUE TITLE
no task source defined

### ISSUE THREAD

**Issue by plehegar** [w3c/page-visibility#1]
[[
The spec uses the concept of "queue a task" but fails to define a task source. Task queues depend on task sources and hence one MUST be explicitly defined or mentioned in the spec. APIs, such as the Screen Orientation API rely on the interaction between when the page visibility values are changed and the event is fired - but because there is no task source, it's not possible to wire them up together using prose :(

See: 
mounirlamouri/screen-orientation@b9737da

I don't know exactly which one to use, maybe the "animation frame task source" - see:
http://lists.w3.org/Archives/Public/www-dom/2014JulSep/0061.html

I imagine there is some interplay between page visibility and requestAnimationFrame(). 
]]
http://lists.w3.org/Archives/Public/public-web-perf/2014Sep/0023.html

**Comment by mounirlamouri** [comment]
- @marcoscaceres 

Is there any ETA for this?

**Comment by marcoscaceres** [comment]
@mounirlamouri, we should probably just start editing the spec.

**Comment by igrigorik** [comment]
If you guys can propose the language, either on the list or via a pull... that'd be awesome.

**Comment by marcoscaceres** [comment]
yeah, we will do a pull

**Comment by marcoscaceres** [comment]
(was not implying forking or taking it over :) ... we are not that crazy :feelsgood: )

**Comment by marcoscaceres** [comment]
Sorry, on my todo...

**Comment by marcoscaceres** [comment]
(sorry, I'm not finding time to do this :( ... can someone else do it?)
