### ISSUE TITLE
Examples are a bit far-fetched

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/page-visibility#10]
The examples in the spec, in indeed the stated motivation for this spec (the development of power and CPU efficient web applications), is a bit far-fetched as currently presented. In particular, the examples  using `setTimeout()` would only yield marginal power savings - turning on the phone radio in the way shown would make @igrigorik cry :) 

The value of the spec is simply in specifying the visibility state of a document in the platform. This primitive then allows other APIs to create more power efficient behavior like "requestAnimationFrame()" or prevent certain things from happening (e.g., preventing rotation changes if the document is hidden). 

I think the spec should be refocused to describe the above (i.e., what it's foundation role is in the web platform).

**Comment by plehegar** [comment]
I agree that the checkEmail example isn't the most illustrative one (especially for mail notification). An animation based example would be way better.

**Comment by furoshiki** [comment]
I agree that checkEmail by polling is a bad practice on mobile performance. But I think animation based example is not way better, because rAF can cover those use cases.

The value of page-visibility is the browser observation ability. Browser can observe active/inactive states and switch application movement. For example, application can pause video streaming, when visibility state becomes hidden.

**Comment by marcoscaceres** [comment]
I agree with @hiroshik850223. The actual value of this API is really all the other platform APIs that hook into it (on its own). What we could do is just acknowledge that, and provide just simple examples of its usage.  

Having said that, there might be some interesting examples from here:
https://github.com/search?l=javascript&q=%22document.hidden%22&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by igrigorik** [comment]
How about a simplified video example? That, and we can site some other instances where similar pattern is useful - e.g. pausing animations, analytics reporting, etc.

``` javascript
var videoElement = document.getElementById("videoElement");

function handleVisibilityChange() {
  if (document.hidden) {
    videoElement.pause();
  } else {
    videoElement.play();
  }
}

// Handle page visibility change   
document.addEventListener(visibilityChange, handleVisibilityChange, false);
```

**Comment by marcoscaceres** [comment]
That sounds much better :)

**Comment by igrigorik** [comment]
@marcoscaceres ptal: https://github.com/w3c/page-visibility/pull/13/files

**Comment by furoshiki** [comment]
Thank you!
