### ISSUE TITLE
doesn't work for lock screen on windows

### ISSUE THREAD

**Issue by pangrr** [w3c/page-visibility#14]
This API seems not able to detect lock screen on Windows 7 with Chrome

**Comment by igrigorik** [comment]
This sounds like an implementation issue, not a spec issue. 

Can you please open a bug on crbug.com?

**Comment by pangrr** [comment]
Already fired a bug here.

On Tue, Sep 15, 2015 at 10:11 AM, Ilya Grigorik notifications@github.com
wrote:

> This sounds like an implementation issue, not a spec issue.
> 
> Can you please open a bug on crbug.com?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/page-visibility/issues/14#issuecomment-140467441.

## 

Ran Pang

**Comment by igrigorik** [comment]
Great, thanks!
