### ISSUE TITLE
Drop 'unloaded' from visibilityState enum

### ISSUE THREAD

**Issue by igrigorik** [w3c/page-visibility#17]
http://w3c.github.io/page-visibility/#visibility-states-and-the-visibilitystate-enum
- This value was marked as optional and no existing implementation supports it.
- As far as I can tell, it's not surfacing anything that you can't already get (e.g. via pagehide).

I propose we drop it from the spec - see https://github.com/w3c/page-visibility/pull/16.

**Comment by toddreifsteck** [comment]
Resolved by #16
