### ISSUE TITLE
Hooks for "the document becomes visible/hidden"

### ISSUE THREAD

**Issue by plehegar** [w3c/page-visibility#2]
[[
The specification has "now visible algorithm" and "now hidden algorithm" but misses extension points at the end of those algorithms. It would be great to add such extension points so other specifications could cleanly define behaviour when the document visibility state changes.
]]
http://lists.w3.org/Archives/Public/public-web-perf/2014Sep/0034.html

**Comment by mounirlamouri** [comment]
CC @marcoscaceres

Any ETA for this?

**Comment by plehegar** [comment]
@mounirlamouri let me know if the hooks are good for you

**Comment by igrigorik** [comment]
Resolved, closing.
