### ISSUE TITLE
w3c must decouple the page visibility api from top level document

### ISSUE THREAD

**Issue by jeffreytgilbert** [w3c/page-visibility#20]
The use of Flash plugins and slow polling mechanisms to determine if a browser has optimized a resource as "out of view" are not web standard behaviors, but are nearly standard behaviors of advertisers. These techniques could be replaced by bringing the offscreen state back to the page visibility api and simply allowing iframes which are sandboxed away from access to a top level document to still be aware of their current state. Scripts could then be paused on these frames saving energy, and reducing the need for complex measurement strategies which heavily impact page load speeds and cause jank when scrolling.

I'm happy to go into more detail as needed, but removing the call for that functionality from the spec is a huge mistake which will be reflected by the slow decay of poorly performant plugins. This also stifles mobile web development as these systems traditionally require access to the top document and cannot be easily sandboxed due to the lack of a comprehensive page visibility api decoupled from the top level document state.

**Comment by jeffreytgilbert** [comment]
Referencing https://github.com/w3c/page-visibility/issues/8 as it calls into question explicit definition for the behavior on iframes

**Comment by plehegar** [comment]
did you look at https://github.com/slightlyoff/IntersectionObserver/blob/master/explainer.md to see if it would fit better your use case?

**Comment by igrigorik** [comment]
+1 to Intersection Observer, that's exactly the problem it's addressing. To follow progress: http://discourse.wicg.io/t/transferring-intersectionobserver-to-the-wicg/1230

**Comment by jeffreytgilbert** [comment]
I've now read the spec and it appears to address my main concerns. One thing of note would be ambiguity in the explainer document around the necessity to include ads.js as part of the top level document or if that would be included in the body of the child iframe. If the API points can be hooked into independently of the sandboxing status of the child iframe, and the intersectionRect and boundingClientRect are broadcast whenever there is a threshold change of any percentage beyond the subscribed threshold (not just when it changes state, as in crossed vs out) then this is what I've been working toward.

**Comment by igrigorik** [comment]
@jeffreytgilbert probably worth opening an issue on the IO repo to clarify :-)

Closing.
