### ISSUE TITLE
Nothing defines the behaviour of Document::onvisibilitychange

### ISSUE THREAD

**Issue by Ms2ger** [w3c/page-visibility#22]

**Comment by igrigorik** [comment]
Doesn't http://w3c.github.io/page-visibility/#reacting-to-visibility-changes do exactly that?

**Comment by Ms2ger** [comment]
No, that just defines when the event is dispatched. You also need to link up the attribute with the event dispatching infrastructure.

**Comment by igrigorik** [comment]
@Ms2ger any chance that can you point me to an example that does this right? :)

**Comment by jyasskin** [comment]
See if you like the way https://webbluetoothcg.github.io/web-bluetooth/#idl-event-handlers does this. I was copying from examples like https://html.spec.whatwg.org/multipage/webappapis.html#event-handlers-on-elements,-document-objects,-and-window-objects.

**Comment by igrigorik** [comment]
@jyasskin thanks! That said, this is still a bit murky to me... What exactly is missing? :)
- We define the eventhandler here: http://w3c.github.io/page-visibility/#extensions-to-the-document-interface
- We define when the event is dispatched here: http://w3c.github.io/page-visibility/#reacting-to-visibility-changes

> "You also need to link up the attribute with the event dispatching infrastructure." 

Are we missing "onvisiblity change is an Event handler attribute for the visibilitychange event type."? Or, is there more to it.

**Comment by jyasskin** [comment]
Specifically, 

> `onvisibilitychange` is an [event handler IDL attribute](https://html.spec.whatwg.org/multipage/webappapis.html#event-handler-idl-attributes) for the `visibilitychange` event type.

to pull in the definition of what happens when script sets and gets the attribute. I believe that's sufficient.

**Comment by igrigorik** [comment]
@jyasskin thanks!

@Ms2ger please review: https://github.com/w3c/page-visibility/pull/23
