### ISSUE TITLE
Relations between page visibility and Visibility API

### ISSUE THREAD

**Issue by plehegar** [w3c/page-visibility#24]
It would valuable to at least ack the Visibility API from the PV spec:
 https://www.w3.org/TR/UISecurity/

**Comment by igrigorik** [comment]
AFAIK, that API is not implemented any browser and my understanding is that a future iteration of  IntersectionObserver may address some of those use cases? Given that there there are no implementations of said API and it's not clear where there will be any.. I'm inclined to suggest that we "ignore" it for now? Happy to revisit if/once we have some real-world implementer interest.

**Comment by igrigorik** [comment]
@plehegar closing, per above. Please feel free to reopen if you feel otherwise.

**Comment by plehegar** [comment]
LGTM.
