### ISSUE TITLE
Transition Level 2 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/page-visibility#25]
- [x] **Known / outstanding spec issues**
  - [x] document updates from L1
  - [x] update ack's section for L2
- [x] **Web platform tests**
  - https://github.com/w3c/web-platform-tests/tree/master/page-visibility
- [x] **Privacy and security**
  - https://github.com/w3c/page-visibility/pull/27
- [ ] **Implementations**
  - Chrome: [M56+](https://bugs.chromium.org/p/chromium/issues/detail?id=554834#c17)
  - Firefox: [M18+](https://developer.mozilla.org/en-US/Firefox/Releases/18#DOM.2FAPIs)
  - Edge: TODO. 
  - Safari: WIP, https://bugs.webkit.org/show_bug.cgi?id=151234
- [x] **Public signals: adoption, feedback...**
  - https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API
  - https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar please review above updates.

I believe the spec itself is good to publish. I reviewed the tests and I believe we have all the bits covered there. The only small gotcha is that only FF currently passes the `unload` test case; I'm hoping we'll land the [fix soon in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=554834) -- currently behind a flag. That said, I don't think this should block us from proceeding with the transition.

**Comment by plehegar** [comment]
👍

**Comment by igrigorik** [comment]
Approved CR transition: https://www.w3.org/2016/10/26-webperf-minutes.html

**Comment by plehegar** [comment]
I republished the document for wide review. Should request the move in 2 weeks since I don't really expect folks to comment on this update.

**Comment by toddreifsteck** [comment]
Microsoft Edge Bug is https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5405698/

**Comment by plehegar** [comment]
I haven't seen additional comments on this front, so I'll request CR status.

**Comment by plehegar** [comment]
scheduled for publication tomorrow

**Comment by plehegar** [comment]
Published at https://www.w3.org/TR/2016/CR-page-visibility-2-20161122/
Next step would be PR in January.

**Comment by igrigorik** [comment]
\o/ ... updated status [on our spreadsheet](https://docs.google.com/spreadsheets/d/1JIB8c7hfyH_wuxkf6bLgovFekHP1LpTtqBTJGEUIK7E/edit), closing this.

Thanks everyone!

**Comment by toddreifsteck** [comment]
Edge has fixed this in private branches. It is "coming soon" to an Insider build!
