### ISSUE TITLE
onvisibilitychange is not implemented

### ISSUE THREAD

**Issue by plehegar** [w3c/page-visibility#31]
We need a test and some implementations
https://github.com/w3c/page-visibility/issues/7
Adding @marcoscaceres since he is the one who requested it.

**Comment by igrigorik** [comment]
Stepping back for a second.. None of the current implementations support `onvisibilitychange`.

> Doesn't http://w3c.github.io/page-visibility/#reacting-to-visibility-changes do exactly that?
>> @Ms2ger No, that just defines when the event is dispatched. You also need to link up the attribute with the event dispatching infrastructure.

As a result, we added onvisibilitychange in https://github.com/w3c/page-visibility/issues/22. That said, I'm yet to hear any developer complain about lack of this feature, and it's holding this spec back from advancing. Should we revisit earlier discussion and reconsider if we need it?

@domenic @annevk do you have any guidance here, from HTML spec side? We fire the event in "[reacting to visibility changes](https://w3c.github.io/page-visibility/#reacting-to-visibilitychange-changes)". Is the `onvisibilitychange` event handler a must, or an optional feature?

**Comment by annevk** [comment]
If you have a `visibilitychange` event you should probably also have an event handler. There's a couple events that don't have a corresponding event handler (only `DOMContentLoaded` comes to mind at the moment) and that's very much exceptional.

**Comment by domenic** [comment]
It's a must: https://w3ctag.github.io/design-principles/#always-add-event-handlers

**Comment by igrigorik** [comment]
@annevk @domenic thanks guys. 

Filed tracking bugs: 
- ~~Webkit: https://bugs.webkit.org/show_bug.cgi?id=174177~~
- Chrome: https://crbug.com/739345
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1333912
- Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12640343


---

@siusin do you have bandwidth to wire up a WPT test for the event handler? We have [existing tests for the event](https://github.com/w3c/web-platform-tests/blob/master/page-visibility/test_minimize-manual.html#L85), I think it should be pretty straightforward to add another handler to that test suite?

**Comment by igrigorik** [comment]
Tests landed in https://github.com/w3c/web-platform-tests/issues/3220, closing this.

In related news, FF [landed support for onvisibilitychange](https://bugzilla.mozilla.org/show_bug.cgi?id=1333912), which will ship in M56. With that, we have two implementations.
