### ISSUE TITLE
It is unclear in PR whether UA may mark hidden when obscured

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/page-visibility#34]
The following is copied from the Page Visibility 2.  It seems to hint that the primary window MAY be hidden when obscured, but is explicit about usability tools not being able to make a window hidden. It seems to be missing an entry in hidden.

Proposed addition:
"The user agent MAY return "hidden" if the window is fully obscured but an accessibility tool is not covering it."

-----------------------------------

Otherwise, return the VisibilityState value that best matches the visibility state of doc: 
Return "visible" if: 
The user agent is not minimized and doc is the foreground tab. 
The user agent is fully obscured by an accessibility tool, like a magnifier, but a view of the doc is shown. 
Return "hidden" if: 
The user agent is minimized. 
The user agent is not minimized, but doc is on a background tab. 
The user agent is to unload doc. 
The Operating System lock screen is shown. 
To accommodate assistive technologies that are typically full screen but still show a view of the page, when applicable, on getting, the [ visibilityState attribute MAY return visible, instead of hidden, when the user agent is not minimized but is fully obscured by other applications.

**Comment by toddreifsteck** [comment]
From TPAC 2017:
Discussed with group. Decision was to update the published spec to ensure Obscure is MAY hidden/visible.

**Comment by toddreifsteck** [comment]
@rniwa
Also please fix the string vs. code formatting.

**Comment by toddreifsteck** [comment]
Also.. investigate the Respec errors.

**Comment by siusin** [comment]
@toddreifsteck @rniwa any update on this issue?

The ReSpec errors have been cleaned up. Thanks to @marcoscaceres .
