### ISSUE TITLE
visibilityState should say which top-level browsing context

### ISSUE THREAD

**Issue by jyasskin** [w3c/page-visibility#41]
https://w3c.github.io/page-visibility/#visibilitystate-attribute says

> On getting, the visibilityState attribute the user agent MUST run the steps to determine the visibility state:
>
> 1. Let doc be the Document of the top level browsing context.
> 1. If the defaultView of doc is null, return "hidden".
> 1. Otherwise, return the VisibilityState value that best matches the visibility state of doc: …

"the [top level browsing context](https://html.spec.whatwg.org/multipage/browsers.html#top-level-browsing-context)" is not uniquely defined. Every tab has its own. I think you mean to say "this Document's [browsing context]()'s top level browsing context." You probably need to check https://html.spec.whatwg.org/multipage/browsers.html#fully-active first to ensure this document has a browsing context at all.

**Comment by toddreifsteck** [comment]
Resolved by #46
