### ISSUE TITLE
Remove prerender test from the test suite

### ISSUE THREAD

**Issue by yoavweiss** [w3c/page-visibility#48]

**Comment by mmocny** [comment]
Looks like [this is the test](https://github.com/web-platform-tests/wpt/blob/master/page-visibility/prerender_call.html), and I guess the context for removal is that prerender state has been deprecated.

**Comment by yoavweiss** [comment]
Indeed! This has been on my "list of small chores" for ages now...

**Comment by mmocny** [comment]
@yoavweiss are you able to review web-platform-tests/wpt/pull/24802 (should be trivial)?

You're not listed as a `suggested_reviewers` for page-visibility tests, but according to [reviewing-tests](https://web-platform-tests.org/reviewing-tests/index.html) apparently "The reviewer can be anyone (other than the original test author) that has the required experience with both the spec under test and with the general test guidelines.", and `suggested_reviewers` is more of an opt-in for notifications?

**Comment by yoavweiss** [comment]
Reviewed and LGTMed! Thank you! :)
