### ISSUE TITLE
Republish editorial Proposed Rec 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/page-visibility#53]
@plehegar @yoavweiss would it be possible to republish the spec on TR? (only editorial changes have been made recently) The exported concepts of "visible" and "hidden" are relied on by other specs, and these only get ingested by Shepherd when the spec shows up on TR.

**Comment by yoavweiss** [comment]
@plehegar - can we republish?

**Comment by siusin** [comment]
There isn't a convenient way to republish a PR.  Shall we move to Rec directly? Once we merge  #45 and #46(the conflicts have been resolved) , we can publish the REC within 2 weeks.

**Comment by marcoscaceres** [comment]
I'm ok to wait for REC.
