### ISSUE TITLE
Lack of clarity on how occlusion behavior interacts with iframes

### ISSUE THREAD

**Issue by kg** [w3c/page-visibility#56]
The spec was somewhat recently updated (https://github.com/w3c/page-visibility/commit/0c5325a842fc3087e8650c156ddf22b541e935c3) to allow UAs to treat a page as "hidden" if its window is suitably occluded by other windows on the user's machine. It's unclear how this interacts with iframes, as the spec does not address them or 'frames' or 'children' directly and the documentation on MDN states that iframe visibility is not occlusion-based or visibility-based and is instead inherited from the parent document (https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API):

`
Visibility states of an <iframe> are the same as the parent document. Hiding an <iframe> using CSS properties (such as display: none;) doesn't trigger visibility events or change the state of the document contained within the frame.
`

Inheriting visibility state from the parent document makes sense when page visibility is about whether a tab is the active tab / whether the browser window is minimized / whether the user's screen is powered off, but when page visibility is about pixel-level occlusion on screen, it becomes surprising for an iframe to have different occlusion behavior from a top-level frame - any web page relying on accurate "i am hidden" notifications will stop getting them if it happens to be embedded in an iframe.

Is MDN's information still correct and the intent of the spec? Is the intent of the spec that child frames should have the same pixel-level occlusion behavior? Is it intended that top-level window occlusion - covering the browser with another window - sets a page as hidden but occluding an iframe with another DOM element or setting it to 'display: none' does not?

**Comment by plehegar** [comment]
This might relate to [What should the visibility api return in display:none iframes?](https://lists.w3.org/Archives/Public/public-web-perf/2011Sep/0037.html)

See also [Page Visibility LC issues](https://www.w3.org/2012/01/visibility-lc-issues.html)

**Comment by plehegar** [comment]
and the thread [This spec is not optimal for iframes](https://lists.w3.org/Archives/Public/public-web-perf/2014Jan/0026.html)

**Comment by yoavweiss** [comment]
This was discussed at the [WebPerfWG call](https://docs.google.com/document/d/e/2PACX-1vQRmNQiYCtmBGHPNyRhWKOW0h6bkI-wL-nMylO1-yqBlKDDrEqPRs5BPNHRGZfWLJYXrGyF0i4GUqbd/pub) ([twice](https://docs.google.com/document/d/e/2PACX-1vRVEHQyqUAOR3f0i_b99huuR783PARUBex3S1RZYLAWrCHc0wHfseVFlhiK9r4QXH0NUs7ww8EF4627/pub))

@plehegar pointed you at previous discussions related to this. Otherwise, [IntersectionObserver](https://w3c.github.io/IntersectionObserver/) V2 should give you the ability to observe in-page occlusion of certain iframes.

Closing, as this is not actionable.
