### ISSUE TITLE
Update spec so Bikeshed can automatically pick up linkable terms

### ISSUE THREAD

**Issue by janiceshiu** [w3c/page-visibility#57]
I asked for this spec to be [added to Bikeshed](https://github.com/tabatkins/bikeshed/issues/1577) so that the [screen orientation spec](https://w3c.github.io/screen-orientation/#dependencies) can reference page visibility terms using [xref](https://respec.org/xref/).

The spec is now on Bikeshed. However, tabatkins noted that Bikeshed cannot parse the spec because it is not formatted to follow [Bikeshed's definition contract](https://tabatkins.github.io/bikeshed/#dfn-contract). I'm happy to take this task on if someone could guide me how to update the spec.

For more details, please check the [Bikeshed issue](https://github.com/tabatkins/bikeshed/issues/1577).

Thank you.

cc @marcoscaceres

**Comment by marcoscaceres** [comment]
Closing as ReSpec conforms to the dfn contract.
