### ISSUE TITLE
Compat issue: document.addEventListener / window.addEventListener('visibilitychange')

### ISSUE THREAD

**Issue by jakub-g** [w3c/page-visibility#68]
I just found out today this compatibility issue:

```js
// works in Chrome, Firefox, Safari
document.addEventListener("visibilitychange", onVisChange);

// works in Chrome, Firefox but NOT in Safari; in Safari it's a no-op
window.addEventListener("visibilitychange", onVisChange);
```

The spec only talks about `Document`, I'm wondering if spec should explicitly state that this should be supported on `window` for better portability?

**Comment by cdumez** [comment]
What version of Safari are you testing? I thought we fixed that not too long ago.

**Comment by jakub-g** [comment]
This was in 12.1 / 13.1, I don't have 14.0 (only can test on BrowserStack)

**Comment by cdumez** [comment]
I just tested and it is working as intended in Safari 14.0. As I said, we fixed this fairly recently. The event was not marked as bubbling in WebKit: http://trac.webkit.org/r260483.

Can be closed? The specification says "Fire a simple event named visibilitychange that bubbles". The "that bubbles" part is what makes the event get dispatched on the Window.

**Comment by jakub-g** [comment]
Awesome. Thx for quick reply and verification 👍
