### ISSUE TITLE
can we drop level?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/page-visibility#70]
I'm wondering if it's cool that we drop the "Level" for this spec and just move it to become a "living standard" going forward? The "level" thing is super confusing, particularly for this spec that has "level" in the current iteration, but previously had "2nd Edition" back in 2013 - see:

https://www.w3.org/TR/page-visibility-1/

Going forward, we  can just keep a record of significant changes in an appropriate section in the spec.

**Comment by yoavweiss** [comment]
We agreed on the calls to drop the level and move to a living standards model.
Let's drop the level number from the spec's URL and title.

/cc @caribouW3 @nicjansma

**Comment by caribouW3** [comment]
@yoavweiss I'm confused, it seems that this spec has another kind of future already decided, discussed at https://github.com/w3c/page-visibility/issues/74 and more practical details in https://github.com/w3c/whatwg-coord/issues/16

**Comment by yoavweiss** [comment]
Apologies, I'm the one that was confused.. You're right and this is to be folded into HTML.

**Comment by yoavweiss** [comment]
Closing to avoid further confusion..
