### ISSUE TITLE
Spec got folded into HTML

### ISSUE THREAD

**Issue by noamr** [w3c/page-visibility#74]
Most of the details of the spec are already part of the HTML spec (the `visibilitychange` event). If we can move `visiblityState` and `hidden` properties to HTML, and add some prose on how browsers can decide that a doc is becoming visible/invisble in other ways (e.g switch tab, mobile app switcher etc), there won't be much left for this spec... maybe it's past its incubation? :)

**Comment by yoavweiss** [comment]
Let's discuss at TPAC

**Comment by noamr** [comment]
> Let's discuss at TPAC

Discussed at TPAC, consensus was that this is OK... OK To close?

**Comment by yoavweiss** [comment]
This is indeed OK to fold into HTML, per the WG discussion.
@caribouW3 - What should we do with this document? Publish as a note for historical purposes? Is the WG decision at TPAC enough or should we send a CFC?

**Comment by caribouW3** [comment]
@yoavweiss It's not time-critical so I'd say that a CfC would be nice, with a decision to end work and publish as a Discontinued Draft: https://www.w3.org/2021/Process-20211102/#abandon-draft

**Comment by marcoscaceres** [comment]
Just +1 from me as editor.

**Comment by caribouW3** [comment]
@plehegar I suppose it's OK to proceed?

**Comment by marcoscaceres** [comment]
We should update TR as this spec text is now obsolete. The README needs to be updated and the repo should be archived.

**Comment by plehegar** [comment]
SGTM. See also https://github.com/w3c/whatwg-coord/issues/16 .

**Comment by yoavweiss** [comment]
Sent a (belated) [CFC](https://lists.w3.org/Archives/Public/public-web-perf/2022Jun/0001.html)

**Comment by yoavweiss** [comment]
CFC passed. @caribouW3 can we publish as Discontinued? Thanks! :)

**Comment by caribouW3** [comment]
Published: https://www.w3.org/TR/2022/DISC-page-visibility-2-20220623/

I'll archive this repository tomorrow.
