### ISSUE TITLE
Prerender not defined

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/page-visibility#9]
Spec says: 

> The Document is loaded in the prerender mode and is not yet visible

But prerender mode is not defined. What spec should be linked there?

**Comment by toddreifsteck** [comment]
We've got prerender standardization in resource hints which is currently an editor's draft, https://github.com/w3c/resource-hints Multiple UAs have implemented prerender in various ways which I'm guessing was the intent of having the mention in the spec. We should clean that up as we move towards a standardized prerender.

**Comment by plehegar** [comment]
Note that, prior to resource hints, we got prerender defined at
 http://microformats.org/wiki/rel-prerender

**Comment by igrigorik** [comment]
resolved via #41, #42.
